// productData.js
const productData = {
  //MEN'S TOP-WEAR
shirts: [
  
  { id: 1, name: 'Levi\'s Casual Shirt', brand: 'Levi\'s', price: 999, img: '/top wear/shirts/p1.avif' },
{ id: 2, name: 'Tommy Hilfiger Check Shirt', brand: 'Tommy Hilfiger', price: 1299, img: '/top wear/shirts/p2.avif' },
{ id: 3, name: 'Levi\'s Denim Shirt', brand: 'Levi\'s', price: 1199, img: '/top wear/shirts/p3.avif' },
{ id: 4, name: 'Tommy Hilfiger Slim Fit Shirt', brand: 'Tommy Hilfiger', price: 1399, img: '/top wear/shirts/p4.avif' },
{ id: 5, name: 'U.S. Polo Assn. Striped Shirt', brand: 'U.S. Polo Assn.', price: 899, img: '/top wear/shirts/p5.avif' },
{ id: 6, name: 'Peter England Formal Shirt', brand: 'Peter England', price: 799, img: '/top wear/shirts/p6.avif' },
{ id: 7, name: 'U.S. Polo Assn. Solid Shirt', brand: 'U.S. Polo Assn.', price: 999, img: '/top wear/shirts/p7.avif' },
{ id: 8, name: 'Peter England Checkered Shirt', brand: 'Peter England', price: 849, img: '/top wear/shirts/p8.avif' },
{ id: 9, name: 'Levi\'s Slim Fit Shirt', brand: 'Levi\'s', price: 1099, img: '/top wear/shirts/p9.avif' },
{ id: 10, name: 'Tommy Hilfiger Classic Shirt', brand: 'Tommy Hilfiger', price: 1399, img: '/top wear/shirts/p10.avif' },

  // Add more shirts here
],
tshirts: [
  { id: 1, name: 'H&M Graphic T-shirt', brand: 'H&M', price: 599, img: '/top wear/tshirts/tshirts (1).avif' },
  { id: 2, name: 'Puma Active Tee', brand: 'Puma', price: 749, img: '/top wear/tshirts/tshirts (2).avif' },
  { id: 3, name: 'Zara Cotton T-shirt', brand: 'Zara', price: 899, img: '/top wear/tshirts/tshirts (3).avif' },
  { id: 4, name: 'Superdry Vintage Tee', brand: 'Superdry', price: 999, img: '/top wear/tshirts/tshirts (4).avif' },
  { id: 5, name: 'Jack & Jones Logo T-shirt', brand: 'Jack & Jones', price: 849, img: '/top wear/tshirts/tshirts (5).avif' },
  { id: 6, name: 'H&M Plain Crew Neck', brand: 'H&M', price: 499, img: '/top wear/tshirts/tshirts (6).avif' },
  { id: 7, name: 'Puma Sportswear Tee', brand: 'Puma', price: 799, img: '/top wear/tshirts/tshirts (7).avif' },
  { id: 8, name: 'Zara Slim Fit Tee', brand: 'Zara', price: 899, img: '/top wear/tshirts/tshirts (8).avif' },
  { id: 9, name: 'Superdry Printed T-shirt', brand: 'Superdry', price: 999, img: '/top wear/tshirts/tshirts (9).avif' },
  { id: 10, name: 'Jack & Jones Round Neck', brand: 'Jack & Jones', price: 849, img: '/top wear/tshirts/tshirts (10).avif' },
],
jackets: [
  { id: 1, name: 'Levi\'s Denim Jacket', brand: 'Levi\'s', price: 999, img: '/top wear/jackets/jackets (1).avif' },
  { id: 2, name: 'The North Face Jacket', brand: 'The North Face', price: 1299, img: '/top wear/jackets/jackets (2).avif' },
  { id: 3, name: 'Columbia Waterproof Jacket', brand: 'Columbia', price: 1099, img: '/top wear/jackets/jackets (3).avif' },
  { id: 4, name: 'Patagonia Winter Jacket', brand: 'Patagonia', price: 1499, img: '/top wear/jackets/jackets (4).avif' },
  { id: 5, name: 'Wrangler Puffer Jacket', brand: 'Wrangler', price: 999, img: '/top wear/jackets/jackets (5).avif' },
  { id: 6, name: 'Carhartt Utility Jacket', brand: 'Carhartt', price: 1199, img: '/top wear/jackets/jackets (6).avif' },
  { id: 7, name: 'Tommy Hilfiger Casual Jacket', brand: 'Tommy Hilfiger', price: 1399, img: '/top wear/jackets/jackets (7).avif' },
  { id: 8, name: 'Diesel Bomber Jacket', brand: 'Diesel', price: 1599, img: '/top wear/jackets/jackets (8).avif' },
  { id: 9, name: 'H&M Lightweight Jacket', brand: 'H&M', price: 799, img: '/top wear/jackets/jackets (9).avif' },
  { id: 10, name: 'Zara Wool Coat', brand: 'Zara', price: 1799, img: '/top wear/jackets/jackets (10).avif' }
],

blazers: [
  { id: 1, name: 'Hugo Boss Slim Fit Blazer', brand: 'Hugo Boss', price: 2999, img: '/top wear/Blazers/b (1).webp' },
  { id: 2, name: 'Zara Tailored Blazer', brand: 'Zara', price: 1999, img: '/top wear/Blazers/b (2).webp' },
  { id: 3, name: 'Tom Ford Wool Blazer', brand: 'Tom Ford', price: 4999, img: '/top wear/Blazers/b (3).webp' },
  { id: 4, name: 'Ralph Lauren Classic Blazer', brand: 'Ralph Lauren', price: 3999, img: '/top wear/Blazers/b (4).webp' },
  { id: 5, name: 'Burberry Check Blazer', brand: 'Burberry', price: 4499, img: '/top wear/Blazers/b (5).webp' },
  { id: 6, name: 'Calvin Klein Blazer', brand: 'Calvin Klein', price: 2799, img: '/top wear/Blazers/b (6).webp' },
  { id: 7, name: 'Reiss Navy Blazer', brand: 'Reiss', price: 2499, img: '/top wear/Blazers/b (7).webp' },
  { id: 8, name: 'Ted Baker Tailored Blazer', brand: 'Ted Baker', price: 2999, img: '/top wear/Blazers/b (8).webp' },
  { id: 9, name: 'Michael Kors Blazer', brand: 'Michael Kors', price: 3299, img: '/top wear/Blazers/b (9).webp' },
  { id: 10, name: 'SuitSupply Wool Blazer', brand: 'SuitSupply', price: 3599, img: '/top wear/Blazers/b (10).webp' }
]
,

formalshirts: [
    { id: 1, name: 'Van Heusen Shirt', brand: 'Van Heusen', price: 999, img: '/top wear/formal shirts/fs (1).avif' },
    { id: 2, name: 'Peter England Shirt', brand: 'Peter England', price: 899, img: '/top wear/formal shirts/fs (2).avif' },
    { id: 3, name: 'Arrow Shirt', brand: 'Arrow', price: 1199, img: '/top wear/formal shirts/fs (3).avif' },
    { id: 4, name: 'Parx Shirt', brand: 'Parx', price: 799, img: '/top wear/formal shirts/fs (4).avif' },
    { id: 5, name: 'Lee Shirt', brand: 'Lee', price: 999, img: '/top wear/formal shirts/fs (5).avif' },
    { id: 6, name: 'Van Heusen Shirt', brand: 'Van Heusen', price: 1099, img: '/top wear/formal shirts/fs (6).avif' },
    { id: 7, name: 'Peter England Shirt', brand: 'Peter England', price: 899, img: '/top wear/formal shirts/fs (7).avif' },
    { id: 8, name: 'Arrow Shirt', brand: 'Arrow', price: 1199, img: '/top wear/formal shirts/fs (8).avif' },
    { id: 9, name: 'Parx Shirt', brand: 'Parx', price: 799, img: '/top wear/formal shirts/fs (9).avif' },
    { id: 10, name: 'Lee Shirt', brand: 'Lee', price: 999, img: '/top wear/formal shirts/fs (10).avif' }
],

   suits: [
    { id: 1, name: 'Hugo Boss Suit', brand: 'Hugo Boss', price: 1499, img: '/top wear/suits/suits (1).webp' },
    { id: 2, name: 'Ralph Lauren Suit', brand: 'Ralph Lauren', price: 1399, img: '/top wear/suits/suits (2).webp' },
    { id: 3, name: 'Tom Ford Suit', brand: 'Tom Ford', price: 2499, img: '/top wear/suits/suits (3).webp' },
    { id: 4, name: 'Armani Suit', brand: 'Armani', price: 1999, img: '/top wear/suits/suits (4).webp' },
    { id: 5, name: 'Zegna Suit', brand: 'Zegna', price: 2299, img: '/top wear/suits/suits (5).webp' },
    { id: 6, name: 'Canali Suit', brand: 'Canali', price: 1699, img: '/top wear/suits/suits (6).webp' },
    { id: 7, name: 'Brioni Suit', brand: 'Brioni', price: 2599, img: '/top wear/suits/suits (7).webp' },
    { id: 8, name: 'Boss Black Suit', brand: 'Boss Black', price: 1799, img: '/top wear/suits/suits (8).webp' },
    { id: 9, name: 'Burberry Suit', brand: 'Burberry', price: 2199, img: '/top wear/suits/suits (9).webp' },
    { id: 10, name: 'J. Crew Suit', brand: 'J. Crew', price: 999, img: '/top wear/suits/suits (10).webp' }
]
,
  sweatshirts: [
    { id: 1, name: 'Nike Sweatshirt', brand: 'Nike', price: 799, img: '/top wear/sweatshirts/sweat (1).avif' },
    { id: 2, name: 'Adidas Sweatshirt', brand: 'Adidas', price: 899, img: '/top wear/sweatshirts/sweat (2).avif' },
    { id: 3, name: 'Puma Sweatshirt', brand: 'Puma', price: 749, img: '/top wear/sweatshirts/sweat (3).avif' },
    { id: 4, name: 'Under Armour Sweatshirt', brand: 'Under Armour', price: 999, img: '/top wear/sweatshirts/sweat (4).avif' },
    { id: 5, name: 'Reebok Sweatshirt', brand: 'Reebok', price: 849, img: '/top wear/sweatshirts/sweat (5).avif' },
    { id: 6, name: 'Fila Sweatshirt', brand: 'Fila', price: 799, img: '/top wear/sweatshirts/sweat (6).avif' },
    { id: 7, name: 'Champion Sweatshirt', brand: 'Champion', price: 999, img: '/top wear/sweatshirts/sweat (7).avif' },
    { id: 8, name: 'Converse Sweatshirt', brand: 'Converse', price: 799, img: '/top wear/sweatshirts/sweat (8).avif' },
    { id: 9, name: 'H&M Sweatshirt', brand: 'H&M', price: 699, img: '/top wear/sweatshirts/sweat (9).avif' },
    { id: 10, name: 'Zara Sweatshirt', brand: 'Zara', price: 799, img: '/top wear/sweatshirts/sweat (10).avif' }
]
,
 

  //WOMEN'S WESTREN-WEAR
 kurtas : [
  { id: 1, name: 'Levi\'s Jeans', brand: 'Manyavar', price: 999, img: '/ethnic wear/kurtas/ku (1).avif' },
  { id: 2, name: 'Wrangler Trousers', brand: 'Fabindia', price: 899, img: '/ethnic wear/kurtas/ku (2).avif' },
  { id: 3, name: 'Levi\'s Jeans', brand: 'Biba', price: 999, img: '/ethnic wear/kurtas/ku (3).avif' },
  { id: 4, name: 'Wrangler Trousers', brand: 'W', price: 899, img: '/ethnic wear/kurtas/ku (4).avif' },
  { id: 5, name: 'Levi\'s Jeans', brand: 'Soch', price: 999, img: '/ethnic wear/kurtas/ku (5).avif' },
  { id: 6, name: 'Wrangler Trousers', brand: 'Aurelia', price: 899, img: '/ethnic wear/kurtas/ku (6).avif' },
  { id: 7, name: 'Levi\'s Jeans', brand: 'Indya', price: 999, img: '/ethnic wear/kurtas/ku (7).avif' },
  { id: 8, name: 'Wrangler Trousers', brand: 'Global Desi', price: 899, img: '/ethnic wear/kurtas/ku (8).avif' },
  { id: 9, name: 'Levi\'s Jeans', brand: 'Jaipur Kurti', price: 999, img: '/ethnic wear/kurtas/ku (9).avif' },
  { id: 10, name: 'Wrangler Trousers', brand: 'Libas', price: 899, img: '/ethnic wear/kurtas/ku (10).avif' },
],

  dresses : [
  { id: 1, name: 'Levi\'s Jeans', brand: 'Zara', price: 999, img: '/dresses/dr(1).avif' },
  { id: 2, name: 'Wrangler Trousers', brand: 'H&M', price: 899, img: '/dresses/dr(2).avif' },
  { id: 3, name: 'Levi\'s Jeans', brand: 'Forever 21', price: 999, img: '/dresses/dr(3).avif' },
  { id: 4, name: 'Wrangler Trousers', brand: 'ONLY', price: 899, img: '/dresses/dr(4).avif' },
  { id: 5, name: 'Levi\'s Jeans', brand: 'Vero Moda', price: 999, img: '/dresses/dr(5).avif' },
  { id: 6, name: 'Wrangler Trousers', brand: 'AND', price: 899, img: '/dresses/dr(6).avif' },
  { id: 7, name: 'Levi\'s Jeans', brand: 'Global Desi', price: 999, img: '/dresses/dr(7).avif' },
  { id: 8, name: 'Wrangler Trousers', brand: 'Biba', price: 899, img: '/dresses/dr(8).avif' },
  { id: 9, name: 'Levi\'s Jeans', brand: 'Faballey', price: 999, img: '/dresses/dr(9).avif' },
  { id: 10, name: 'Wrangler Trousers', brand: 'Koovs', price: 899, img: '/dresses/dr(10).avif' },
],
   tops: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'ONLY', price: 999, img: '/tops/top (1).avif' },
  { id: 2, name: 'Wrangler Trousers', brand: 'Vero Moda', price: 899, img: '/tops/top (2).avif' },
  { id: 3, name: 'Levi\'s Jeans', brand: 'H&M', price: 999, img: '/tops/top (3).avif' },
  { id: 4, name: 'Wrangler Trousers', brand: 'Zara', price: 899, img: '/tops/top (4).avif' },
  { id: 5, name: 'Levi\'s Jeans', brand: 'Forever 21', price: 999, img: '/tops/top (5).avif' },
  { id: 6, name: 'Wrangler Trousers', brand: 'Faballey', price: 899, img: '/tops/top (6).avif' },
  { id: 7, name: 'Levi\'s Jeans', brand: 'AND', price: 999, img: '/tops/top (7).avif' },
  { id: 8, name: 'Wrangler Trousers', brand: 'Global Desi', price: 899, img: '/tops/top (8).avif' },
  { id: 9, name: 'Levi\'s Jeans', brand: 'Mango', price: 999, img: '/tops/top (9).avif' },
  { id: 10, name: 'Wrangler Trousers', brand: 'ONLY', price: 899, img: '/tops/top (10).avif' },
],
   sarees: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   jackets1: [
   { id: 1, name: 'Levi\'s Jeans', brand: 'Superdry', price: 999, img: '/jackets/ja (1).avif' },
  { id: 2, name: 'Wrangler Trousers', brand: 'Zara', price: 899, img: '/jackets/ja (2).avif' },
  { id: 3, name: 'Levi\'s Jeans', brand: 'H&M', price: 999, img: '/jackets/ja (3).avif' },
  { id: 4, name: 'Wrangler Trousers', brand: 'Woodland', price: 899, img: '/jackets/ja (4).avif' },
  { id: 5, name: 'Levi\'s Jeans', brand: 'Puma', price: 999, img: '/jackets/ja (5).avif' },
  { id: 6, name: 'Wrangler Trousers', brand: 'Nike', price: 899, img: '/jackets/ja (6).avif' },
  { id: 7, name: 'Levi\'s Jeans', brand: 'Jack & Jones', price: 999, img: '/jackets/ja (7).avif' },
  { id: 8, name: 'Wrangler Trousers', brand: 'The North Face', price: 899, img: '/jackets/ja (8).avif' },
  { id: 9, name: 'Levi\'s Jeans', brand: 'Columbia', price: 999, img: '/jackets/ja (9).avif' },
  { id: 10, name: 'Wrangler Trousers', brand: 'Decathlon', price: 899, img: '/jackets/ja (10).avif' },
],
   jeans: [
    { id: 1, name: 'Slim Fit Jeans', brand: 'Levi\'s', price: 999, img: '/jeans/je (1).avif' },
  { id: 2, name: 'Straight Fit Jeans', brand: 'Wrangler', price: 899, img: '/jeans/je (2).avif' },
  { id: 3, name: 'Tapered Jeans', brand: 'Lee', price: 999, img: '/jeans/je (3).avif' },
  { id: 4, name: 'Skinny Jeans', brand: 'Diesel', price: 899, img: '/jeans/je (4).avif' },
  { id: 5, name: 'Bootcut Jeans', brand: 'Pepe Jeans', price: 999, img: '/jeans/je (5).avif' },
  { id: 6, name: 'Ripped Jeans', brand: 'Calvin Klein', price: 899, img: '/jeans/je (6).avif' },
  { id: 7, name: 'High Rise Jeans', brand: 'Tommy Hilfiger', price: 999, img: '/jeans/je (7).avif' },
  { id: 8, name: 'Relaxed Fit Jeans', brand: 'Spykar', price: 899, img: '/jeans/je (8).avif' },
  { id: 9, name: 'Loose Fit Jeans', brand: 'Flying Machine', price: 999, img: '/jeans/je (9).avif' },
  { id: 10, name: 'Mid Rise Jeans', brand: 'Mufti', price: 899, img: '/jeans/je (10).avif' },
],
   tshirt1: [
    { id: 1, name: 'Graphic T-Shirt', brand: 'Nike', price: 999, img: '/t-shirt/ts (1).avif' },
  { id: 2, name: 'Crew Neck Tee', brand: 'Adidas', price: 899, img: '/t-shirt/ts (2).avif' },
  { id: 3, name: 'Plain White Tee', brand: 'Puma', price: 999, img: '/t-shirt/ts (3).avif' },
  { id: 4, name: 'Printed T-Shirt', brand: 'Superdry', price: 899, img: '/t-shirt/ts (4).avif' },
  { id: 5, name: 'Oversized T-Shirt', brand: 'H&M', price: 999, img: '/t-shirt/ts (5).avif' },
  { id: 6, name: 'Colorblock Tee', brand: 'Zara', price: 899, img: '/t-shirt/ts (6).avif' },
  { id: 7, name: 'V-Neck T-Shirt', brand: 'Tommy Hilfiger', price: 999, img: '/t-shirt/ts (7).avif' },
  { id: 8, name: 'Henley T-Shirt', brand: 'Jack & Jones', price: 899, img: '/t-shirt/ts (8).avif' },
  { id: 9, name: 'Polo T-Shirt', brand: 'U.S. Polo Assn.', price: 999, img: '/t-shirt/ts (9).avif' },
  { id: 10, name: 'Slim Fit Tee', brand: 'Roadster', price: 899, img: '/t-shirt/ts (10).avif' },
],
   trousers: [
    { id: 1, name: 'Formal Trousers', brand: 'Arrow', price: 999, img: '/trouser/trou (1).avif' },
  { id: 2, name: 'Slim Fit Trousers', brand: 'Van Heusen', price: 899, img: '/trouser/trou (2).avif' },
  { id: 3, name: 'Flat Front Trousers', brand: 'Peter England', price: 999, img: '/trouser/trou (3).avif' },
  { id: 4, name: 'Cotton Trousers', brand: 'Allen Solly', price: 899, img: '/trouser/trou (4).avif' },
  { id: 5, name: 'Casual Trousers', brand: 'Park Avenue', price: 999, img: '/trouser/trou (5).avif' },
  { id: 6, name: 'Regular Fit Trousers', brand: 'Blackberrys', price: 899, img: '/trouser/trou (6).avif' },
  { id: 7, name: 'Stretchable Trousers', brand: 'John Players', price: 999, img: '/trouser/trou (7).avif' },
  { id: 8, name: 'Chino Trousers', brand: 'U.S. Polo Assn.', price: 899, img: '/trouser/trou (8).avif' },
  { id: 9, name: 'Linen Trousers', brand: 'Raymond', price: 999, img: '/trouser/trou (9).avif' },
  { id: 10, name: 'Classic Trousers', brand: 'Louis Philippe', price: 899, img: '/trouser/trou (10).avif' },
],
   shirts1: [
    { id: 1, name: 'Formal Shirt', brand: 'Van Heusen', price: 999, img: '/shirts/shi (1).avif' },
  { id: 2, name: 'Classic Shirt', brand: 'Arrow', price: 899, img: '/shirts/shi (2).avif' },
  { id: 3, name: 'Slim Fit Shirt', brand: 'Peter England', price: 999, img: '/shirts/shi (3).avif' },
  { id: 4, name: 'Cotton Shirt', brand: 'Louis Philippe', price: 899, img: '/shirts/shi (4).avif' },
  { id: 5, name: 'Plain Formal Shirt', brand: 'Raymond', price: 999, img: '/shirts/shi (5).avif' },
  { id: 6, name: 'Button-Down Shirt', brand: 'Blackberrys', price: 899, img: '/shirts/shi (6).avif' },
  { id: 7, name: 'Solid Shirt', brand: 'Allen Solly', price: 999, img: '/shirts/shi (7).avif' },
  { id: 8, name: 'Textured Shirt', brand: 'Park Avenue', price: 899, img: '/shirts/shi (8).avif' },
  { id: 9, name: 'Office Wear Shirt', brand: 'John Players', price: 999, img: '/shirts/shi (9).avif' },
  { id: 10, name: 'Premium Formal Shirt', brand: 'Marks & Spencer', price: 899, img: '/shirts/shi (10).avif' },
],
   sweaters: [
    { id: 1, name: 'Wool Blend Sweater', brand: 'GAP', price: 999, img: '/sweater/sw (1).avif' },
  { id: 2, name: 'Crew Neck Sweater', brand: 'H&M', price: 899, img: '/sweater/sw (2).avif' },
  { id: 3, name: 'Cotton Sweater', brand: 'Uniqlo', price: 999, img: '/sweater/sw (3).avif' },
  { id: 4, name: 'V-Neck Sweater', brand: 'Tommy Hilfiger', price: 899, img: '/sweater/sw (4).avif' },
  { id: 5, name: 'Knit Sweater', brand: 'Zara', price: 999, img: '/sweater/sw (5).avif' },
  { id: 6, name: 'Winter Sweater', brand: 'Jack & Jones', price: 899, img: '/sweater/sw (6).avif' },
  { id: 7, name: 'Patterned Sweater', brand: 'Pepe Jeans', price: 999, img: '/sweater/sw (7).avif' },
  { id: 8, name: 'Half-Zip Sweater', brand: 'Calvin Klein', price: 899, img: '/sweater/sw (8).avif' },
  { id: 9, name: 'Slim Fit Sweater', brand: 'Roadster', price: 999, img: '/sweater/sw (9).avif' },
  { id: 10, name: 'Classic Fit Sweater', brand: 'U.S. Polo Assn.', price: 899, img: '/sweater/sw (10).avif' },
],
   coats: [
    { id: 1, name: 'Trench Coat', brand: 'Burberry', price: 999, img: '/coats/c (1).jpeg' },
  { id: 2, name: 'Parka Jacket', brand: 'The North Face', price: 899, img: '/coats/c (2).jpeg' },
  { id: 3, name: 'Wool Coat', brand: 'Zara', price: 999, img: '/coats/c (3).jpeg' },
  { id: 4, name: 'Down Coat', brand: 'H&M', price: 899, img: '/coats/c (4).jpeg' },
  { id: 5, name: 'Peacoat', brand: 'Tommy Hilfiger', price: 999, img: '/coats/c (5).jpeg' },
  { id: 6, name: 'Overcoat', brand: 'Calvin Klein', price: 899, img: '/coats/c (6).jpeg' },
  { id: 7, name: 'Puffer Jacket', brand: 'Columbia', price: 999, img: '/coats/c (7).jpeg' },
  { id: 8, name: 'Fleece Jacket', brand: 'Uniqlo', price: 899, img: '/coats/c (8).jpeg' },
  { id: 9, name: 'Rain Coat', brand: 'Patagonia', price: 999, img: '/coats/c (9).jpeg' },
  { id: 10, name: 'Classic Coat', brand: 'Jack & Jones', price: 899, img: '/coats/c (10).jpeg' },
],
   blazers: [
      { id: 1, name: 'Classic Fit Blazer', brand: 'Raymond', price: 999, img: '/blazers/b(1).webp' },
  { id: 2, name: 'Slim Fit Blazer', brand: 'Van Heusen', price: 899, img: '/blazers/b(2).webp' },
  { id: 3, name: 'Single Breasted Blazer', brand: 'Allen Solly', price: 999, img: '/blazers/b(3).webp' },
  { id: 4, name: 'Double Breasted Blazer', brand: 'Blackberrys', price: 899, img: '/blazers/b(4).webp' },
  { id: 5, name: 'Tweed Blazer', brand: 'Park Avenue', price: 999, img: '/blazers/b(5).webp' },
  { id: 6, name: 'Velvet Blazer', brand: 'Louis Philippe', price: 899, img: '/blazers/b(6).webp' },
  { id: 7, name: 'Checked Blazer', brand: 'Zara', price: 999, img: '/blazers/b(7).webp' },
  { id: 8, name: 'Formal Blazer', brand: 'H&M', price: 899, img: '/blazers/b(8).webp' },
  { id: 9, name: 'Textured Blazer', brand: 'Arrow', price: 999, img: '/blazers/b(9).webp' },
  { id: 10, name: 'Party Wear Blazer', brand: 'Selected Homme', price: 899, img: '/blazers/b(10).webp' },
  ],
   skirts: [
    { id: 1, name: 'Pleated Midi Skirt', brand: 'Zara', price: 999, img: '/skirts/ski (1).avif' },
  { id: 2, name: 'Denim Mini Skirt', brand: 'H&M', price: 899, img: '/skirts/ski (2).avif' },
  { id: 3, name: 'A-Line Skirt', brand: 'Forever 21', price: 999, img: '/skirts/ski (3).avif' },
  { id: 4, name: 'Floral Skirt', brand: 'Mango', price: 899, img: '/skirts/ski (4).avif' },
  { id: 5, name: 'Wrap Skirt', brand: 'AND', price: 999, img: '/skirts/ski (5).avif' },
  { id: 6, name: 'High Waist Skirt', brand: 'ONLY', price: 899, img: '/skirts/ski (6).avif' },
  { id: 7, name: 'Pencil Skirt', brand: 'Marks & Spencer', price: 999, img: '/skirts/ski (7).avif' },
  { id: 8, name: 'Ruffle Skirt', brand: 'Vero Moda', price: 899, img: '/skirts/ski (8).avif' },
  { id: 9, name: 'Slit Skirt', brand: 'FabAlley', price: 999, img: '/skirts/ski (9).avif' },
  { id: 10, name: 'Maxi Skirt', brand: 'Global Desi', price: 899, img: '/skirts/ski (10).avif' },
  ],

// mens bottom wear 

jeans1: [
    { id: 1, name: 'Slim Fit Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/jeans/j1.avif' },
  { id: 2, name: 'Regular Fit Jeans', brand: 'Wrangler', price: 899, img: '/bottom wears/jeans/j2.webp' },
  { id: 3, name: 'Tapered Jeans', brand: 'Diesel', price: 999, img: '/bottom wears/jeans/j3.avif' },
  { id: 4, name: 'Skinny Fit Jeans', brand: 'Pepe Jeans', price: 899, img: '/bottom wears/jeans/j4.webp' },
  { id: 5, name: 'Bootcut Jeans', brand: 'Lee', price: 999, img: '/bottom wears/jeans/j5.webp' },
  { id: 6, name: 'Distressed Jeans', brand: 'Flying Machine', price: 899, img: '/bottom wears/jeans/j6.avif' },
  { id: 7, name: 'High Rise Jeans', brand: 'Killer', price: 999, img: '/bottom wears/jeans/j7.webp' },
  { id: 8, name: 'Low Rise Jeans', brand: 'Spykar', price: 899, img: '/bottom wears/jeans/j8.avif' },
  { id: 9, name: 'Straight Fit Jeans', brand: 'Jack & Jones', price: 999, img: '/bottom wears/jeans/j9.avif' },
  { id: 10, name: 'Relaxed Fit Jeans', brand: 'Mufti', price: 899, img: '/bottom wears/jeans/j10.avif' },
],

  shorts1: [
     { id: 1, name: 'Athletic Shorts', brand: 'Nike', price: 999, img: '/bottom wears/shorts/short (1).avif' },
  { id: 2, name: 'Running Shorts', brand: 'Adidas', price: 899, img: '/bottom wears/shorts/short (2).avif' },
  { id: 3, name: 'Cotton Shorts', brand: 'Puma', price: 999, img: '/bottom wears/shorts/short (3).avif' },
  { id: 4, name: 'Training Shorts', brand: 'Under Armour', price: 899, img: '/bottom wears/shorts/short (4).avif' },
  { id: 5, name: 'Gym Shorts', brand: 'Reebok', price: 999, img: '/bottom wears/shorts/short (5).avif' },
  { id: 6, name: 'Denim Shorts', brand: 'Levi\'s', price: 899, img: '/bottom wears/shorts/short (6).avif' },
  { id: 7, name: 'Lounge Shorts', brand: 'HRX', price: 999, img: '/bottom wears/shorts/short (7).avif' },
  { id: 8, name: 'Cargo Shorts', brand: 'U.S. Polo Assn.', price: 899, img: '/bottom wears/shorts/short (8).avif' },
  { id: 9, name: 'Chino Shorts', brand: 'Jack & Jones', price: 999, img: '/bottom wears/shorts/short (9).avif' },
  { id: 10, name: 'Printed Shorts', brand: 'Roadster', price: 899, img: '/bottom wears/shorts/short (10).avif' },
],

  joggers: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/joggers/jo (1).webp' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/joggers/jo (2).webp' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/joggers/jo (3).webp' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/joggers/jo (4).webp' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/joggers/jo (5).webp' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/joggers/jo (6).webp' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/joggers/jo (7).webp' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/joggers/jo (8).webp' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/joggers/jo (9).webp' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/joggers/jo (10).webp' },
    // Add more pants here
  ],

  trousers: [
   { id: 1, name: 'Slim Fit Trousers', brand: 'Uniqlo', price: 999, img: '/bottom wears/trousers/t1.jpeg' },
  { id: 2, name: 'Khaki Trousers', brand: 'Dockers', price: 899, img: '/bottom wears/trousers/t2.webp' },
  { id: 3, name: 'Formal Trousers', brand: 'Van Heusen', price: 999, img: '/bottom wears/trousers/t3.jpeg' },
  { id: 4, name: 'Stretch Fit Trousers', brand: 'Levi\'s', price: 899, img: '/bottom wears/trousers/t4.webp' },
  { id: 5, name: 'Chino Trousers', brand: 'Wrangler', price: 999, img: '/bottom wears/trousers/t5.jpeg' },
  { id: 6, name: 'Bootcut Trousers', brand: 'Calvin Klein', price: 899, img: '/bottom wears/trousers/t6.webp' },
  { id: 7, name: 'Casual Trousers', brand: 'Tommy Hilfiger', price: 999, img: '/bottom wears/trousers/t7.jpeg' },
  { id: 8, name: 'Tapered Fit Trousers', brand: 'J.Crew', price: 899, img: '/bottom wears/trousers/t8.jpeg' },
  { id: 9, name: 'Flat Front Trousers', brand: 'H&M', price: 999, img: '/bottom wears/trousers/t9.jpeg' },
  { id: 10, name: 'Straight Fit Trousers', brand: 'Zara', price: 899, img: '/bottom wears/trousers/t10.jpeg' },
],

  trackpants: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/trackpants/k1.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/trackpants/k2.webp' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/trackpants/k3.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/trackpants/k4.webp' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/trackpants/k5.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/trackpants/k6.avif' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/trackpants/k7.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/trackpants/k8.avif' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/trackpants/k9.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/trackpants/k10.avif' },
    // Add more pants here
  ],

  underwears: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/underwares/u1.webp' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/underwares/u2.avif' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/underwares/u3.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/underwares/u4.avif' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/underwares/u5.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/underwares/u6.avif' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/underwares/u7.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/underwares/u8.avif' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: '/bottom wears/underwares/u9.avif' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: '/bottom wears/underwares/u10.jpg' },
    // Add more pants here
  ],

  //WOMEN'S WESTERN-WEAR

   kurtasets: [
    { id: 1, name: 'Elegant Kurta Set', brand: 'Manyavar', price: 999, img: 'kurta sets/ks(1).jpeg' },
  { id: 2, name: 'Classic Ethnic Wear', brand: 'Fabindia', price: 899, img: 'kurta sets/ks(2).jpeg' },
  { id: 3, name: 'Festive Kurta Combo', brand: 'Biba Men', price: 1049, img: 'kurta sets/ks(3).jpeg' },
  { id: 4, name: 'Traditional Kurta Set', brand: 'Kisah', price: 949, img: 'kurta sets/ks(4).jpeg' },
  { id: 5, name: 'Designer Kurta Duo', brand: 'Sojanya', price: 1199, img: 'kurta sets/ks(5).jpeg' },
  { id: 6, name: 'Premium Cotton Kurta', brand: 'Tathastu', price: 999, img: 'kurta sets/ks(6).jpeg' },
  { id: 7, name: 'Royal Festive Wear', brand: 'Pothys', price: 1099, img: 'kurta sets/ks(7).jpeg' },
  { id: 8, name: 'Modern Ethnic Set', brand: 'Vastramay', price: 949, img: 'kurta sets/ks(8).jpeg' },
  { id: 9, name: 'Stylish Kurta Pack', brand: 'Raymond Ethnix', price: 1249, img: 'kurta sets/ks(9).jpeg' },
  { id: 10, name: 'Graceful Indian Wear', brand: 'Jompers', price: 899, img: 'kurta sets/ks(10).jpeg' }
]
,

   ethnicdresses: [
     { id: 1, name: 'Floral Anarkali Dress', brand: 'Global Desi', price: 1299, img: 'et(1).jpeg' },
  { id: 2, name: 'Straight Kurta Set', brand: 'Biba', price: 1399, img: 'ethnic dresses/et (2).jpeg' },
  { id: 3, name: 'Printed A-Line Kurti', brand: 'W for Woman', price: 1199, img: 'ethnic dresses/et (3).avif' },
  { id: 4, name: 'Festive Ethnic Gown', brand: 'Aurelia', price: 1499, img: 'ethnic dresses/et(4).avif' },
  { id: 5, name: 'Chanderi Kurta Combo', brand: 'Libas', price: 1349, img: 'ethnic dresses/et (5).avif' },
  { id: 6, name: 'Embroidered Ethnic Wear', brand: 'Soch', price: 1599, img: 'ethnic dresses/et (6).avif' },
  { id: 7, name: 'Mirror Work Dress', brand: 'Rain & Rainbow', price: 1449, img: 'ethnic dresses/et (7).avif' },
  { id: 8, name: 'Bandhani Print Kurti', brand: 'Indya', price: 1249, img: 'ethnic dresses/et (8).avif' },
  { id: 9, name: 'Handloom Cotton Dress', brand: 'Chhabra 555', price: 1399, img: 'ethnic dresses/et (9).avif' },
  { id: 10, name: 'Elegant Festive Kurta', brand: 'Melange by Lifestyle', price: 1299, img: 'ethnic dresses/et (10).avif' }
],

   tunics: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'tu (1).jpeg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],

   palazzospants: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],

   dupattas: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],

   leggings: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],

   chudidhars: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],

   salwars: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],

   lehangas: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],

  //MEN'S ETHNIC-WEAR
 kurthas: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'ethnic wear/kurtas/ku (1).jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   sherwani: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   waistcoats: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'ethnic wear/waistcoats/w (1).webp' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   trousers: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   pyjamas: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   salwars: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],

  //WOMEN'S NIGHT-WEAR
   nightpyjamas: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   nightsuits: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   sleepovertops: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   bras: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   sleepovershorts: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   briefs: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],
   camisoles: [
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'camisoles/ca (1).jpeg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    { id: 1, name: 'Levi\'s Jeans', brand: 'Levi\'s', price: 999, img: 'levis-jeans.jpg' },
    { id: 2, name: 'Wrangler Trousers', brand: 'Wrangler', price: 899, img: 'wrangler-trousers.jpg' },
    // Add more pants here
  ],


   

};

export default productData;
